/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as InvitoRouteImport } from './routes/invito'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppCatalogoRouteImport } from './routes/_app/catalogo'
import { Route as AppLegheIndexRouteImport } from './routes/_app/leghe/index'
import { Route as AppLegheLeagueIdRouteImport } from './routes/_app/leghe/$leagueId'
import { Route as AppLegheNuovaRouteImport } from './routes/_app/leghe/nuova'
import { Route as AppLegheLeagueIdIndexRouteImport } from './routes/_app/leghe/$leagueId/index'
import { Route as AppLegheLeagueIdAstaRouteImport } from './routes/_app/leghe/$leagueId/asta'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitoRoute = InvitoRouteImport.update({
  id: '/invito',
  path: '/invito',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCatalogoRoute = AppCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => AppRoute,
} as any)
const AppLegheIndexRoute = AppLegheIndexRouteImport.update({
  id: '/leghe/',
  path: '/leghe/',
  getParentRoute: () => AppRoute,
} as any)
const AppLegheLeagueIdRoute = AppLegheLeagueIdRouteImport.update({
  id: '/leghe/$leagueId',
  path: '/leghe/$leagueId',
  getParentRoute: () => AppRoute,
} as any)
const AppLegheNuovaRoute = AppLegheNuovaRouteImport.update({
  id: '/leghe/nuova',
  path: '/leghe/nuova',
  getParentRoute: () => AppRoute,
} as any)
const AppLegheLeagueIdIndexRoute = AppLegheLeagueIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLegheLeagueIdRoute,
} as any)
const AppLegheLeagueIdAstaRoute = AppLegheLeagueIdAstaRouteImport.update({
  id: '/asta',
  path: '/asta',
  getParentRoute: () => AppLegheLeagueIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invito': typeof InvitoRoute
  '/login': typeof LoginRoute
  '/catalogo': typeof AppCatalogoRoute
  '/leghe/$leagueId': typeof AppLegheLeagueIdRouteWithChildren
  '/leghe/nuova': typeof AppLegheNuovaRoute
  '/leghe/': typeof AppLegheIndexRoute
  '/leghe/$leagueId/asta': typeof AppLegheLeagueIdAstaRoute
  '/leghe/$leagueId/': typeof AppLegheLeagueIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invito': typeof InvitoRoute
  '/login': typeof LoginRoute
  '/catalogo': typeof AppCatalogoRoute
  '/leghe/nuova': typeof AppLegheNuovaRoute
  '/leghe': typeof AppLegheIndexRoute
  '/leghe/$leagueId/asta': typeof AppLegheLeagueIdAstaRoute
  '/leghe/$leagueId': typeof AppLegheLeagueIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/invito': typeof InvitoRoute
  '/login': typeof LoginRoute
  '/_app/catalogo': typeof AppCatalogoRoute
  '/_app/leghe/$leagueId': typeof AppLegheLeagueIdRouteWithChildren
  '/_app/leghe/nuova': typeof AppLegheNuovaRoute
  '/_app/leghe/': typeof AppLegheIndexRoute
  '/_app/leghe/$leagueId/asta': typeof AppLegheLeagueIdAstaRoute
  '/_app/leghe/$leagueId/': typeof AppLegheLeagueIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invito'
    | '/login'
    | '/catalogo'
    | '/leghe/$leagueId'
    | '/leghe/nuova'
    | '/leghe/'
    | '/leghe/$leagueId/asta'
    | '/leghe/$leagueId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invito'
    | '/login'
    | '/catalogo'
    | '/leghe/nuova'
    | '/leghe'
    | '/leghe/$leagueId/asta'
    | '/leghe/$leagueId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/invito'
    | '/login'
    | '/_app/catalogo'
    | '/_app/leghe/$leagueId'
    | '/_app/leghe/nuova'
    | '/_app/leghe/'
    | '/_app/leghe/$leagueId/asta'
    | '/_app/leghe/$leagueId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  InvitoRoute: typeof InvitoRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invito': {
      id: '/invito'
      path: '/invito'
      fullPath: '/invito'
      preLoaderRoute: typeof InvitoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/catalogo': {
      id: '/_app/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof AppCatalogoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leghe/': {
      id: '/_app/leghe/'
      path: '/leghe'
      fullPath: '/leghe/'
      preLoaderRoute: typeof AppLegheIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leghe/$leagueId': {
      id: '/_app/leghe/$leagueId'
      path: '/leghe/$leagueId'
      fullPath: '/leghe/$leagueId'
      preLoaderRoute: typeof AppLegheLeagueIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leghe/nuova': {
      id: '/_app/leghe/nuova'
      path: '/leghe/nuova'
      fullPath: '/leghe/nuova'
      preLoaderRoute: typeof AppLegheNuovaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leghe/$leagueId/': {
      id: '/_app/leghe/$leagueId/'
      path: '/'
      fullPath: '/leghe/$leagueId/'
      preLoaderRoute: typeof AppLegheLeagueIdIndexRouteImport
      parentRoute: typeof AppLegheLeagueIdRoute
    }
    '/_app/leghe/$leagueId/asta': {
      id: '/_app/leghe/$leagueId/asta'
      path: '/asta'
      fullPath: '/leghe/$leagueId/asta'
      preLoaderRoute: typeof AppLegheLeagueIdAstaRouteImport
      parentRoute: typeof AppLegheLeagueIdRoute
    }
  }
}

interface AppLegheLeagueIdRouteChildren {
  AppLegheLeagueIdAstaRoute: typeof AppLegheLeagueIdAstaRoute
  AppLegheLeagueIdIndexRoute: typeof AppLegheLeagueIdIndexRoute
}

const AppLegheLeagueIdRouteChildren: AppLegheLeagueIdRouteChildren = {
  AppLegheLeagueIdAstaRoute: AppLegheLeagueIdAstaRoute,
  AppLegheLeagueIdIndexRoute: AppLegheLeagueIdIndexRoute,
}

const AppLegheLeagueIdRouteWithChildren =
  AppLegheLeagueIdRoute._addFileChildren(AppLegheLeagueIdRouteChildren)

interface AppRouteChildren {
  AppCatalogoRoute: typeof AppCatalogoRoute
  AppLegheLeagueIdRoute: typeof AppLegheLeagueIdRouteWithChildren
  AppLegheNuovaRoute: typeof AppLegheNuovaRoute
  AppLegheIndexRoute: typeof AppLegheIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCatalogoRoute: AppCatalogoRoute,
  AppLegheLeagueIdRoute: AppLegheLeagueIdRouteWithChildren,
  AppLegheNuovaRoute: AppLegheNuovaRoute,
  AppLegheIndexRoute: AppLegheIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  InvitoRoute: InvitoRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
