// <auto-generated />
using System;
using Fantastiche.Infrastructure.Common.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fantastiche.Infrastructure.Common.Persistence.Migrations
{
    [DbContext(typeof(FantasticheDbContext))]
    partial class FantasticheDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fantastiche.Infrastructure.Auctions.AuctionSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentPosition")
                        .HasColumnType("int");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LeagueSeasonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ListVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LeagueSeasonId")
                        .IsUnique()
                        .HasFilter("[Status] < 2");

                    b.HasIndex("ListVersionId");

                    b.HasIndex("LeagueSeasonId", "LeagueId");

                    b.ToTable("AuctionSessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_AuctionSessions_CurrentPosition", "[CurrentPosition] >= 0");

                            t.HasCheckConstraint("CK_AuctionSessions_Status", "[Status] IN (0, 1, 2)");

                            t.HasCheckConstraint("CK_AuctionSessions_Version", "[Version] >= 1");
                        });
                });

            modelBuilder.Entity("Fantastiche.Infrastructure.Auctions.Bid", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AcceptedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LeagueSeasonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerAuctionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("PlayerAuctionId", "Sequence")
                        .IsUnique();

                    b.HasIndex("PlayerAuctionId", "LeagueSeasonId", "LeagueId");

                    b.HasIndex("TeamId", "LeagueSeasonId", "LeagueId");

                    b.ToTable("Bids", null, t =>
                        {
                            t.HasCheckConstraint("CK_Bids_Amount", "[Amount] > 0");
                        });
                });

            modelBuilder.Entity("Fantastiche.Infrastructure.Auctions.BudgetMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LeagueSeasonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerAuctionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlayerAuctionId")
                        .IsUnique();

                    b.HasIndex("PlayerAuctionId", "LeagueSeasonId", "LeagueId");

                    b.HasIndex("TeamId", "LeagueSeasonId", "LeagueId");

                    b.ToTable("BudgetMovements", null, t =>
                        {
                            t.HasCheckConstraint("CK_BudgetMovements_Amount", "[Amount] < 0");
                        });
                });

            modelBuilder.Entity("Fantastiche.Infrastructure.Auctions.CallOrderEntry", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LeagueSeasonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("SessionId", "TeamId");

                    b.HasIndex("SessionId", "Position")
                        .IsUnique();

                    b.HasIndex("SessionId", "LeagueSeasonId", "LeagueId");

                    b.HasIndex("TeamId", "LeagueSeasonId", "LeagueId");

                    b.ToTable("CallOrderEntries", (string)null);
                });

            modelBuilder.Entity("Fantastiche.Infrastructure.Auctions.CommandReceipt", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("SessionId", "UserId", "RequestId");

                    b.HasIndex("UserId");

                    b.ToTable("CommandReceipts", (string)null);
                });

            modelBuilder.Entity("Fantastiche.Infrastructure.Auctions.PlayerAuction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BidSequence")
                        .HasColumnType("int");

                    b.Property<Guid>("CallerTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CurrentAmount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Deadline")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("IncrementOptionsJson")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LeagueSeasonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ListVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .IsFixedLength();

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("WinningTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique()
                        .HasFilter("[Status] = 0");

                    b.HasIndex("Deadline", "Id")
                        .HasFilter("[Status] = 0");

                    b.HasIndex("ListVersionId", "PlayerId");

                    b.HasIndex("SessionId", "Number")
                        .IsUnique();

                    b.HasIndex("CallerTeamId", "LeagueSeasonId", "LeagueId");

                    b.HasIndex("WinningTeamId", "LeagueSeasonId", "LeagueId");

                    b.HasIndex("SessionId", "LeagueSeasonId", "LeagueId", "ListVersionId");

                    b.ToTable("PlayerAuctions", null, t =>
                        {
                            t.HasCheckConstraint("CK_PlayerAuctions_CurrentAmount", "[CurrentAmount] > 0");

                            t.HasCheckConstraint("CK_PlayerAuctions_DurationSeconds", "[DurationSeconds] IN (5, 10, 15, 20, 25, 30)");

                            t.HasCheckConstraint("CK_PlayerAuctions_Role", "[Role] IN (N'P', N'D', N'C', N'A')");

                            t.HasCheckConstraint("CK_PlayerAuctions_Status", "[Status] IN (0, 1)");
                        });
                });

            modelBuilder.Entity("Fantastiche.Infrastructure.Auctions.RosterEntry", b =>
                {
                    b.Property<Guid>("LeagueSeasonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AcquiredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerAuctionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .IsFixedLength();

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LeagueSeasonId", "PlayerId");

                    b.HasIndex("PlayerAuctionId")
                        .IsUnique();

                    b.HasIndex("PlayerId");

                    b.HasIndex("PlayerAuctionId", "LeagueSeasonId", "LeagueId");

                    b.HasIndex("TeamId", "LeagueSeasonId", "LeagueId");

                    b.ToTable("RosterEntries", null, t =>
                        {
                            t.HasCheckConstraint("CK_RosterEntries_Price", "[Price] > 0");

                            t.HasCheckConstraint("CK_RosterEntries_Role", "[Role] IN (N'P', N'D', N'C', N'A')");
                        });
                });

            modelBuilder.Entity("Fantastiche.Infrastructure.Catalog.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Source", "NormalizedName")
                        .IsUnique();

                    b.ToTable("Clubs", (string)null);
                });

            modelBuilder.Entity("Fantastiche.Infrastructure.Catalog.ClubMedia", b =>
                {
                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedClubName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long>("ContentLength")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("DownloadedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Source", "NormalizedClubName");

                    b.ToTable("ClubMedia", null, t =>
                        {
                            t.HasCheckConstraint("CK_ClubMedia_ContentLength", "[ContentLength] > 0");
                        });
                });

            modelBuilder.Entity("Fantastiche.Infrastructure.Catalog.ListEntry", b =>
                {
                    b.Property<Guid>("ListVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClubName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PreferredFoot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .IsFixedLength();

                    b.HasKey("ListVersionId", "PlayerId");

                    b.HasIndex("ClubId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ListVersionId", "Role", "ClubName");

                    b.ToTable("ListEntries", (string)null);
                });

            modelBuilder.Entity("Fantastiche.Infrastructure.Catalog.ListVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EntryCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SeasonName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Source", "SeasonName", "ContentHash")
                        .IsUnique();

                    b.HasIndex("Status", "SeasonName", "CreatedAt");

                    b.ToTable("ListVersions", (string)null);
                });

            modelBuilder.Entity("Fantastiche.Infrastructure.Catalog.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Source", "ExternalId")
                        .IsUnique();

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("Fantastiche.Infrastructure.Catalog.PlayerMedia", b =>
                {
                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long>("ContentLength")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("DownloadedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Source", "ExternalId");

                    b.ToTable("PlayerMedia", null, t =>
                        {
                            t.HasCheckConstraint("CK_PlayerMedia_ContentLength", "[ContentLength] > 0");
                        });
                });

            modelBuilder.Entity("Fantastiche.Infrastructure.Common.Authentication.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex")
                        .HasFilter("[NormalizedEmail] IS NOT NULL");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Fantastiche.Infrastructure.Emails.EmailMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("InvitationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ProtectedPayload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("ToAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("InvitationId");

                    b.HasIndex("Status", "NextAttemptAt", "LeaseExpiresAt");

                    b.ToTable("EmailMessages", (string)null);
                });

            modelBuilder.Entity("Fantastiche.Infrastructure.Leagues.League", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LogoBlobName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Leagues", (string)null);
                });

            modelBuilder.Entity("Fantastiche.Infrastructure.Leagues.LeagueInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("AcceptedTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LeagueSeasonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("LeagueId", "UserId");

                    b.HasIndex("LeagueSeasonId", "LeagueId");

                    b.HasIndex("AcceptedTeamId", "LeagueSeasonId", "LeagueId");

                    b.HasIndex("LeagueSeasonId", "UserId", "Kind");

                    b.ToTable("LeagueInvitations", (string)null);
                });

            modelBuilder.Entity("Fantastiche.Infrastructure.Leagues.LeagueMember", b =>
                {
                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsOrganizer")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("LeagueId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("LeagueMembers", (string)null);
                });

            modelBuilder.Entity("Fantastiche.Infrastructure.Leagues.LeagueSeason", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Budget")
                        .HasColumnType("int");

                    b.Property<int>("Defenders")
                        .HasColumnType("int");

                    b.Property<int>("Forwards")
                        .HasColumnType("int");

                    b.Property<int>("Goalkeepers")
                        .HasColumnType("int");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ListVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Midfielders")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ListVersionId");

                    b.HasIndex("LeagueId", "Name")
                        .IsUnique();

                    b.ToTable("LeagueSeasons", null, t =>
                        {
                            t.HasCheckConstraint("CK_LeagueSeasons_Rules", "[Budget] > 0 AND [Goalkeepers] >= 0 AND [Defenders] >= 0 AND [Midfielders] >= 0 AND [Forwards] >= 0 AND ([Goalkeepers]+[Defenders]+[Midfielders]+[Forwards]) > 0 AND [Budget] >= ([Goalkeepers]+[Defenders]+[Midfielders]+[Forwards])");
                        });
                });

            modelBuilder.Entity("Fantastiche.Infrastructure.Teams.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Budget")
                        .HasColumnType("int");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LeagueSeasonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("LeagueSeasonId", "LeagueId");

                    b.HasIndex("LeagueSeasonId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("Teams", null, t =>
                        {
                            t.HasCheckConstraint("CK_Teams_Budget", "[Budget] >= 0");
                        });
                });

            modelBuilder.Entity("Fantastiche.Infrastructure.Teams.TeamMember", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LeagueSeasonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TeamId", "UserId");

                    b.HasIndex("LeagueId", "UserId");

                    b.HasIndex("LeagueSeasonId", "UserId")
                        .IsUnique();

                    b.HasIndex("TeamId", "LeagueSeasonId", "LeagueId");

                    b.ToTable("TeamMembers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Fantastiche.Infrastructure.Auctions.AuctionSession", b =>
                {
                    b.HasOne("Fantastiche.Infrastructure.Common.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fantastiche.Infrastructure.Catalog.ListVersion", null)
                        .WithMany()
                        .HasForeignKey("ListVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fantastiche.Infrastructure.Leagues.LeagueSeason", null)
                        .WithMany()
                        .HasForeignKey("LeagueSeasonId", "LeagueId")
                        .HasPrincipalKey("Id", "LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fantastiche.Infrastructure.Auctions.Bid", b =>
                {
                    b.HasOne("Fantastiche.Infrastructure.Common.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fantastiche.Infrastructure.Auctions.PlayerAuction", null)
                        .WithMany()
                        .HasForeignKey("PlayerAuctionId", "LeagueSeasonId", "LeagueId")
                        .HasPrincipalKey("Id", "LeagueSeasonId", "LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fantastiche.Infrastructure.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "LeagueSeasonId", "LeagueId")
                        .HasPrincipalKey("Id", "LeagueSeasonId", "LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fantastiche.Infrastructure.Auctions.BudgetMovement", b =>
                {
                    b.HasOne("Fantastiche.Infrastructure.Auctions.PlayerAuction", null)
                        .WithMany()
                        .HasForeignKey("PlayerAuctionId", "LeagueSeasonId", "LeagueId")
                        .HasPrincipalKey("Id", "LeagueSeasonId", "LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fantastiche.Infrastructure.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "LeagueSeasonId", "LeagueId")
                        .HasPrincipalKey("Id", "LeagueSeasonId", "LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fantastiche.Infrastructure.Auctions.CallOrderEntry", b =>
                {
                    b.HasOne("Fantastiche.Infrastructure.Auctions.AuctionSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId", "LeagueSeasonId", "LeagueId")
                        .HasPrincipalKey("Id", "LeagueSeasonId", "LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fantastiche.Infrastructure.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "LeagueSeasonId", "LeagueId")
                        .HasPrincipalKey("Id", "LeagueSeasonId", "LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fantastiche.Infrastructure.Auctions.CommandReceipt", b =>
                {
                    b.HasOne("Fantastiche.Infrastructure.Auctions.AuctionSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fantastiche.Infrastructure.Common.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fantastiche.Infrastructure.Auctions.PlayerAuction", b =>
                {
                    b.HasOne("Fantastiche.Infrastructure.Catalog.ListEntry", null)
                        .WithMany()
                        .HasForeignKey("ListVersionId", "PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fantastiche.Infrastructure.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("CallerTeamId", "LeagueSeasonId", "LeagueId")
                        .HasPrincipalKey("Id", "LeagueSeasonId", "LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fantastiche.Infrastructure.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("WinningTeamId", "LeagueSeasonId", "LeagueId")
                        .HasPrincipalKey("Id", "LeagueSeasonId", "LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fantastiche.Infrastructure.Auctions.AuctionSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId", "LeagueSeasonId", "LeagueId", "ListVersionId")
                        .HasPrincipalKey("Id", "LeagueSeasonId", "LeagueId", "ListVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fantastiche.Infrastructure.Auctions.RosterEntry", b =>
                {
                    b.HasOne("Fantastiche.Infrastructure.Catalog.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fantastiche.Infrastructure.Auctions.PlayerAuction", null)
                        .WithMany()
                        .HasForeignKey("PlayerAuctionId", "LeagueSeasonId", "LeagueId")
                        .HasPrincipalKey("Id", "LeagueSeasonId", "LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fantastiche.Infrastructure.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "LeagueSeasonId", "LeagueId")
                        .HasPrincipalKey("Id", "LeagueSeasonId", "LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fantastiche.Infrastructure.Catalog.ListEntry", b =>
                {
                    b.HasOne("Fantastiche.Infrastructure.Catalog.Club", null)
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fantastiche.Infrastructure.Catalog.ListVersion", null)
                        .WithMany()
                        .HasForeignKey("ListVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fantastiche.Infrastructure.Catalog.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fantastiche.Infrastructure.Catalog.ListVersion", b =>
                {
                    b.HasOne("Fantastiche.Infrastructure.Common.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fantastiche.Infrastructure.Emails.EmailMessage", b =>
                {
                    b.HasOne("Fantastiche.Infrastructure.Leagues.LeagueInvitation", null)
                        .WithMany()
                        .HasForeignKey("InvitationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fantastiche.Infrastructure.Leagues.LeagueInvitation", b =>
                {
                    b.HasOne("Fantastiche.Infrastructure.Common.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fantastiche.Infrastructure.Leagues.LeagueMember", null)
                        .WithMany()
                        .HasForeignKey("LeagueId", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fantastiche.Infrastructure.Leagues.LeagueSeason", null)
                        .WithMany()
                        .HasForeignKey("LeagueSeasonId", "LeagueId")
                        .HasPrincipalKey("Id", "LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fantastiche.Infrastructure.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("AcceptedTeamId", "LeagueSeasonId", "LeagueId")
                        .HasPrincipalKey("Id", "LeagueSeasonId", "LeagueId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Fantastiche.Infrastructure.Leagues.LeagueMember", b =>
                {
                    b.HasOne("Fantastiche.Infrastructure.Leagues.League", null)
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fantastiche.Infrastructure.Common.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fantastiche.Infrastructure.Leagues.LeagueSeason", b =>
                {
                    b.HasOne("Fantastiche.Infrastructure.Leagues.League", null)
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fantastiche.Infrastructure.Catalog.ListVersion", null)
                        .WithMany()
                        .HasForeignKey("ListVersionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Fantastiche.Infrastructure.Teams.Team", b =>
                {
                    b.HasOne("Fantastiche.Infrastructure.Leagues.LeagueSeason", null)
                        .WithMany()
                        .HasForeignKey("LeagueSeasonId", "LeagueId")
                        .HasPrincipalKey("Id", "LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fantastiche.Infrastructure.Teams.TeamMember", b =>
                {
                    b.HasOne("Fantastiche.Infrastructure.Leagues.LeagueMember", null)
                        .WithMany()
                        .HasForeignKey("LeagueId", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fantastiche.Infrastructure.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "LeagueSeasonId", "LeagueId")
                        .HasPrincipalKey("Id", "LeagueSeasonId", "LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Fantastiche.Infrastructure.Common.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Fantastiche.Infrastructure.Common.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fantastiche.Infrastructure.Common.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Fantastiche.Infrastructure.Common.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
